### ISSUE TITLE
Hard to read in dark mode

### ISSUE THREAD

**Issue by OboTheHobo** [danzilberdan/obsidian-mathlive#4]
While editing certain parts of an equation in dark mode, it gets highlighted in a color which makes it very hard to read
(I apologize if this is an issue with something else and not this particular plugin in specific, I'm not sure exactly how obsidian works)

Screenshot attached.
![Screenshot_20231003_110642](https://github.com/danzilberdan/obsidian-mathlive/assets/36374109/4cdbec3a-03b2-4da8-bd61-72f15c00fe4b)

It also gets highlighted in light mode, but it's very readable in light mode.

On Fedora Linux 38 if it matters.

**Comment by Helmoes** [comment]
I noticed this too. I practically don't know CSS but through trial and error I got a css snippet that's tolerable.

```
.modal {
    width: 60vw;
    max-width: 80vw;
    max-height: 80vh;
}

.mathlive-modal-content {
    display: flex;
    flex-direction: row;
    justify-content: space-around;
    align-items: flex-end;
    padding-top: 1rem;
    align-content: center;
    flex-wrap: wrap;
}

math-field {
    font-size: var(--font-text-size);
    min-width: 60%;
    max-width: 80%;
    overflow: visible;
    --selection-background-color: var(--text-selection);
}

math-field::part(content) {
    --_text-highlight-background-color: #1e1e1e;
    --_contains-highlight-background-color: #1e1e1e;
}

.submit {
    float: right;
    background-color: green !important;
    color: white;
}
```
