### ISSUE TITLE
2 Suggestions

### ISSUE THREAD

**Issue by BananenRitter** [danzilberdan/obsidian-mathlive#5]
Thank you very much you make my academic life a lot easier! Now i can learn LaTeX on the go while working effectively.

1. Youve done a great job implementing keyboard input on the virtual keyboard. However i am missing switching between the 4 tabs (numeric, symbol, roman greek) with a press of the hardware keyboard. I suggest using the Tab key for this. Tab is currently used for switching to the insert button and this closes the virtual keyboard. I suggest you implement pressing enter to close the virtual keyboard. After that you could either press tab again to go to the insert button or pressing enter again for insertin (for this the cursor has to jump to the insert button after pressing enter the first time

2. It would be great to have an option on a free place on the virtual keyboard where you can toggle if you want to use inline $examplecode$ or outline $$examplecode$$ LaTeX instead of always using outline by default before inserting

**Comment by danzilberdan** [comment]
Point 2. Is already implemented.
I added "using enter to insert" to the backlog.
